// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-GP7yBHqpDr6tKYzGKUzKiBTb22z3Rsg',
    appId: '1:460705186239:web:8d9912ec64ae068abae10a',
    messagingSenderId: '460705186239',
    projectId: 'skill-rate',
    authDomain: 'skill-rate.firebaseapp.com',
    storageBucket: 'skill-rate.appspot.com',
    measurementId: 'G-QBCD6ZM0PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLrao9aV4ySSh9v6VwrywQ08RKV8inho',
    appId: '1:460705186239:android:efd6e74339b35171bae10a',
    messagingSenderId: '460705186239',
    projectId: 'skill-rate',
    storageBucket: 'skill-rate.appspot.com',
  );
}
